package hu.bute.daai.amorg.drtorrent.analytics.entity;
// Generated 2013.12.29. 20:16:51 by Hibernate Tools 3.2.1.GA



/**
 * Powerinfo generated by hbm2java
 */
public class Powerinfo  implements java.io.Serializable {


     private Long id;
     private Peer peer;
     private long fromDate;
     private long toDate;
     private boolean isPlugged;

    public Powerinfo() {
    }

    public Powerinfo(Peer peer, long fromDate, long toDate, boolean isPlugged) {
       this.peer = peer;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.isPlugged = isPlugged;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Peer getPeer() {
        return this.peer;
    }
    
    public void setPeer(Peer peer) {
        this.peer = peer;
    }
    public long getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(long fromDate) {
        this.fromDate = fromDate;
    }
    public long getToDate() {
        return this.toDate;
    }
    
    public void setToDate(long toDate) {
        this.toDate = toDate;
    }
    public boolean isIsPlugged() {
        return this.isPlugged;
    }
    
    public void setIsPlugged(boolean isPlugged) {
        this.isPlugged = isPlugged;
    }




}


