package hu.bute.daai.amorg.drtorrent.analytics.entity;
// Generated 2013.12.29. 20:16:51 by Hibernate Tools 3.2.1.GA



/**
 * Process generated by hbm2java
 */
public class Process  implements java.io.Serializable {


     private Long id;
     private Torrent torrent;
     private Peer peer;
     private long addedOn;
     private int badPieces;
     private int goodPieces;
     private int failedConnections;
     private int tcpConnections;
     private int handshakes;
     private long downloaded;
     private long completed;
     private long uploaded;
     private long downloadingTime;
     private long seedingTime;
     private long completedOn;
     private long removedOn;

    public Process() {
    }

    public Process(Torrent torrent, Peer peer, long addedOn, int badPieces, int goodPieces, int failedConnections, int tcpConnections, int handshakes, long downloaded, long completed, long uploaded, long downloadingTime, long seedingTime, long completedOn, long removedOn) {
       this.torrent = torrent;
       this.peer = peer;
       this.addedOn = addedOn;
       this.badPieces = badPieces;
       this.goodPieces = goodPieces;
       this.failedConnections = failedConnections;
       this.tcpConnections = tcpConnections;
       this.handshakes = handshakes;
       this.downloaded = downloaded;
       this.completed = completed;
       this.uploaded = uploaded;
       this.downloadingTime = downloadingTime;
       this.seedingTime = seedingTime;
       this.completedOn = completedOn;
       this.removedOn = removedOn;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Torrent getTorrent() {
        return this.torrent;
    }
    
    public void setTorrent(Torrent torrent) {
        this.torrent = torrent;
    }
    public Peer getPeer() {
        return this.peer;
    }
    
    public void setPeer(Peer peer) {
        this.peer = peer;
    }
    public long getAddedOn() {
        return this.addedOn;
    }
    
    public void setAddedOn(long addedOn) {
        this.addedOn = addedOn;
    }
    public int getBadPieces() {
        return this.badPieces;
    }
    
    public void setBadPieces(int badPieces) {
        this.badPieces = badPieces;
    }
    public int getGoodPieces() {
        return this.goodPieces;
    }
    
    public void setGoodPieces(int goodPieces) {
        this.goodPieces = goodPieces;
    }
    public int getFailedConnections() {
        return this.failedConnections;
    }
    
    public void setFailedConnections(int failedConnections) {
        this.failedConnections = failedConnections;
    }
    public int getTcpConnections() {
        return this.tcpConnections;
    }
    
    public void setTcpConnections(int tcpConnections) {
        this.tcpConnections = tcpConnections;
    }
    public int getHandshakes() {
        return this.handshakes;
    }
    
    public void setHandshakes(int handshakes) {
        this.handshakes = handshakes;
    }
    public long getDownloaded() {
        return this.downloaded;
    }
    
    public void setDownloaded(long downloaded) {
        this.downloaded = downloaded;
    }
    public long getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(long completed) {
        this.completed = completed;
    }
    public long getUploaded() {
        return this.uploaded;
    }
    
    public void setUploaded(long uploaded) {
        this.uploaded = uploaded;
    }
    public long getDownloadingTime() {
        return this.downloadingTime;
    }
    
    public void setDownloadingTime(long downloadingTime) {
        this.downloadingTime = downloadingTime;
    }
    public long getSeedingTime() {
        return this.seedingTime;
    }
    
    public void setSeedingTime(long seedingTime) {
        this.seedingTime = seedingTime;
    }
    public long getCompletedOn() {
        return this.completedOn;
    }
    
    public void setCompletedOn(long completedOn) {
        this.completedOn = completedOn;
    }
    public long getRemovedOn() {
        return this.removedOn;
    }
    
    public void setRemovedOn(long removedOn) {
        this.removedOn = removedOn;
    }




}


