package hu.bute.daai.amorg.drtorrent.analytics.entity;
// Generated 2013.12.29. 20:16:51 by Hibernate Tools 3.2.1.GA



/**
 * Networkinfo generated by hbm2java
 */
public class Networkinfo  implements java.io.Serializable {


     private Long id;
     private Peer peer;
     private long fromDate;
     private long toDate;
     private int networkType;

    public Networkinfo() {
    }

    public Networkinfo(Peer peer, long fromDate, long toDate, int networkType) {
       this.peer = peer;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.networkType = networkType;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Peer getPeer() {
        return this.peer;
    }
    
    public void setPeer(Peer peer) {
        this.peer = peer;
    }
    public long getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(long fromDate) {
        this.fromDate = fromDate;
    }
    public long getToDate() {
        return this.toDate;
    }
    
    public void setToDate(long toDate) {
        this.toDate = toDate;
    }
    public int getNetworkType() {
        return this.networkType;
    }
    
    public void setNetworkType(int networkType) {
        this.networkType = networkType;
    }




}


