package hu.bute.daai.amorg.drtorrent.analytics.entity;
// Generated 2013.04.13. 16:49:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Peer generated by hbm2java
 */
public class Peer  implements java.io.Serializable {


     private Long id;
     private String peerIdentifier;
     private Set<Process> processes = new HashSet<Process>(0);

    public Peer() {
    }

	
    public Peer(String peerIdentifier) {
        this.peerIdentifier = peerIdentifier;
    }
    public Peer(String peerIdentifier, Set<Process> processes) {
       this.peerIdentifier = peerIdentifier;
       this.processes = processes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPeerIdentifier() {
        return this.peerIdentifier;
    }
    
    public void setPeerIdentifier(String peerIdentifier) {
        this.peerIdentifier = peerIdentifier;
    }
    public Set<Process> getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set<Process> processes) {
        this.processes = processes;
    }




}


