package hu.bute.daai.amorg.drtorrent.analytics.entity;
// Generated 2013.04.13. 16:49:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Torrent generated by hbm2java
 */
public class Torrent  implements java.io.Serializable {


     private Long id;
     private String infoHash;
     private long size;
     private int pieces;
     private Set<Process> processes = new HashSet<Process>(0);

    public Torrent() {
    }

	
    public Torrent(String infoHash, long size, int pieces) {
        this.infoHash = infoHash;
        this.size = size;
        this.pieces = pieces;
    }
    public Torrent(String infoHash, long size, int pieces, Set<Process> processes) {
       this.infoHash = infoHash;
       this.size = size;
       this.pieces = pieces;
       this.processes = processes;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getInfoHash() {
        return this.infoHash;
    }
    
    public void setInfoHash(String infoHash) {
        this.infoHash = infoHash;
    }
    public long getSize() {
        return this.size;
    }
    
    public void setSize(long size) {
        this.size = size;
    }
    public int getPieces() {
        return this.pieces;
    }
    
    public void setPieces(int pieces) {
        this.pieces = pieces;
    }
    public Set<Process> getProcesses() {
        return this.processes;
    }
    
    public void setProcesses(Set<Process> processes) {
        this.processes = processes;
    }




}


